### ISSUE TITLE
Add pylint to git actions

### ISSUE THREAD

**Issue by ryanjameskennedy** [ryanjameskennedy/jasentool#20]
The following could be added to `.github/workflows/pylint.yml`:
```
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -e .[dev]
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under 9 $(git ls-files '*.py')
```
